# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AbletonOscMcp < Formula
  desc "MCP server for controlling Ableton Live via AbletonOSC"
  homepage "https://github.com/nozomi-koborinai/ableton-osc-mcp"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.5.0/ableton-osc-mcp-darwin-amd64"
      sha256 "f78a983418ae0df6ace6d08d0e22388487d139df1ee896330da251e009574af3"

      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.5.0/ableton-osc-mcp-darwin-arm64"
      sha256 "25d34c4085f79b3f0041bb2c38471cd907cc0b60a3c86ddef5b250d873d744ca"

      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.5.0/ableton-osc-mcp-linux-amd64"
      sha256 "c4701cc897f29975feeea07e032a38e7d6aa89c2bd636070d36f354afde4b437"
      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.5.0/ableton-osc-mcp-linux-arm64"
      sha256 "58cf1ed460f097705f19f8d48a988b2ff9cb57eea3c647a0a77cbe1a64b9158e"
      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
  end

  test do
    assert_predicate bin/"ableton-osc-mcp", :executable?
  end
end
