# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AbletonOscMcp < Formula
  desc "MCP server for controlling Ableton Live via AbletonOSC"
  homepage "https://github.com/nozomi-koborinai/ableton-osc-mcp"
  version "0.2.0-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.2.0-alpha/ableton-osc-mcp-darwin-amd64"
      sha256 "bf5459e69bbee1f8631c1c254289f342847e47c11776fda10faa257e9c729ade"

      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.2.0-alpha/ableton-osc-mcp-darwin-arm64"
      sha256 "6ccaee4fc206a836e9ba262e76a75d02df91abad0a7a1b8e1be61b9283af98c8"

      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.2.0-alpha/ableton-osc-mcp-linux-amd64"
      sha256 "7d12e32ccfcca7c5baad6222793d0e11f89dc3be47b8ef1ae7f6689c588d282b"
      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/ableton-osc-mcp/releases/download/v0.2.0-alpha/ableton-osc-mcp-linux-arm64"
      sha256 "ace369a7a7fd422cbf14d209e161d34ac350d63f00ab4f44220f342df5508590"
      define_method(:install) do
        bin.install Dir["ableton-osc-mcp*"].first => "ableton-osc-mcp"
      end
    end
  end

  test do
    assert_predicate bin/"ableton-osc-mcp", :executable?
  end
end
