# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpCostMcpServer < Formula
  desc "MCP server for estimating Google Cloud running costs"
  homepage "https://github.com/nozomi-koborinai/gcp-cost-mcp-server"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.8.0/gcp-cost-mcp-server-darwin-amd64"
      sha256 "b0c4896583685dce15aab347b7a6ffc5e28d790869720bb4a4a3d5a39a0a7796"

      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.8.0/gcp-cost-mcp-server-darwin-arm64"
      sha256 "83ac6dc2107be787f063a2ebd59b4e4ed1b45bb1698693a20d6dee33c92c541d"

      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.8.0/gcp-cost-mcp-server-linux-amd64"
      sha256 "6ef44fd4f067b1f2ffe8de427c750c6e7eb81f4b190c26d4b428664d2bd51a43"
      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.8.0/gcp-cost-mcp-server-linux-arm64"
      sha256 "a95b7eb0f27640d5ff58bd01947da7733ddc95efc4df71afd8610241206881c5"
      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"gcp-cost-mcp-server", :executable?
  end
end
