# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpCostMcpServer < Formula
  desc "MCP server for estimating Google Cloud running costs"
  homepage "https://github.com/nozomi-koborinai/gcp-cost-mcp-server"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.6.0/gcp-cost-mcp-server-darwin-amd64"
      sha256 "278ce59a7d261b2476236380bd71f351dafd645f9c54b0df28da4f230c4ca956"

      def install
        bin.install "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.6.0/gcp-cost-mcp-server-darwin-arm64"
      sha256 "52b43f17e2ff33cde4d1a8554c9f0ac14fa6a361692578e6795c1c0c4c06c5a1"

      def install
        bin.install "gcp-cost-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.6.0/gcp-cost-mcp-server-linux-amd64"
      sha256 "8c2f0241cee1d56b1e5d0aed73293b5007c71b8661a35ab64dab7d93a22d6437"
      def install
        bin.install "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.6.0/gcp-cost-mcp-server-linux-arm64"
      sha256 "55722f463d1d2c24b0465c1b8d994ed9bb1dcd39257c56e9295fcddc541e079b"
      def install
        bin.install "gcp-cost-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"gcp-cost-mcp-server", :executable?
  end
end
