# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpCostMcpServer < Formula
  desc "MCP server for estimating Google Cloud running costs"
  homepage "https://github.com/nozomi-koborinai/gcp-cost-mcp-server"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.9.0/gcp-cost-mcp-server-darwin-amd64"
      sha256 "aa390fcd6f438345215341b14d8a3cf7b8ed75324dd6658d4743c9362e578aa3"

      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.9.0/gcp-cost-mcp-server-darwin-arm64"
      sha256 "699d316ac07fccd0cd9dfc3b9dc0d460f41de1065599a29716be2ad60b0b6f22"

      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.9.0/gcp-cost-mcp-server-linux-amd64"
      sha256 "1c453ba3c652068e8e9ec46fb5a09200968af6b30d76c211920dba901444d810"
      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nozomi-koborinai/gcp-cost-mcp-server/releases/download/v0.9.0/gcp-cost-mcp-server-linux-arm64"
      sha256 "b15846c54a298a73c5961ee5b966f8add6a6bf93f309c827db16fc4c21f2b56d"
      define_method(:install) do
        bin.install Dir["gcp-cost-mcp-server*"].first => "gcp-cost-mcp-server"
      end
    end
  end

  test do
    assert_predicate bin/"gcp-cost-mcp-server", :executable?
  end
end
